config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :legal_cases
  resources :clients
  patch 'clients/:id/edit', to: 'clients#edit'

  root to: 'pages#index' do
    get 'clients'
    get 'legal_cases'
  end


  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 devise_scope :user do
   get 'login', to: 'devise/sessions#new'
 end

 devise_scope :user do
   get 'signup', to: 'devise/registrations#new'
 end


# get '/button', to: 'your_controller_name#button` , as: 'button'




end

app/controllers/legal_cases_controller.rb
class LegalCasesController < ApplicationController
  before_action :set_legal_case, only: [:show, :edit, :update, :destroy]
#the controller is only concerned with the HTTP request/response cycle.
  # GET /legal_cases
  # GET /legal_cases.json
  def index
    @legal_cases = LegalCase.all
  end

  # GET /legal_cases/1
  # GET /legal_cases/1.json
  def show
    @legal_case = LegalCase.find(params[:id])
  end

  # GET /legal_cases/new
  def new
    @legal_case = LegalCase.new
  end

  # GET /legal_cases/1/edit
  def edit
  end

  # POST /legal_cases
  # POST /legal_cases.json
  def create
    @legal_case = LegalCase.new(legal_case_params)

    respond_to do |format|
      if @legal_case.save
        format.html { redirect_to @legal_case, notice: 'Legal case was successfully created.' }
        format.json { render :show, status: :created, location: @legal_case }
      else
        format.html { render :new }
        format.json { render json: @legal_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_cases/1
  # PATCH/PUT /legal_cases/1.json
  def update
    respond_to do |format|
      if @legal_case.update(legal_case_params)
        format.html { redirect_to @legal_case, notice: 'Legal case was successfully updated.' }
        format.json { render :show, status: :ok, location: @legal_case }
      else
        format.html { render :edit }
        format.json { render json: @legal_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_cases/1
  # DELETE /legal_cases/1.json
  def destroy
    @legal_case.destroy
    respond_to do |format|
      format.html { redirect_to legal_cases_url, notice: 'Legal case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_case
      @legal_case = LegalCase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_case_params
      params.require(:legal_case).permit(:caseID, :isActive, :country)
    end
end

app/helpers/legal_cases_helper.rb
module LegalCasesHelper
end

app/views/legal_cases/_form.html.erb
<%= form_with(model: legal_case, local: true) do |form| %>
  <% if legal_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(legal_case.errors.count, "error") %> prohibited this legal_case from being saved:</h2>

      <ul>
      <% legal_case.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caseID %>
    <%= form.text_field :caseID %>
  </div>

  <div class="field">
    <%= form.label :isActive %>
    <%= form.check_box :isActive %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.button :submit %>
  </div>
<% end %>

app/views/legal_cases/_legal_cases.html.erb
<h4 class="legalcase-text">
  <%= truncate(legal_case.caseID, :length => 60) %>
</h4>
<div class="legalcase-content">
  <h3><%= legal_case.name %></h3>
  <p><%= legal_case.country %></p>
</div>

app/views/legal_cases/edit.html.erb
<h1>Editing Legal Case</h1>

<%= render 'form', legal_case: @legal_case %>

<%= link_to 'Show', @legal_case %> |
<%= link_to 'Back', legal_cases_path %>

app/views/legal_cases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Legal Cases</h1>

<table>
  <thead>
    <tr>
      <th>Caseid</th>
      <th>Isactive</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legal_cases.each do |legal_case| %>
      <tr>
        <td><%= legal_case.caseID %></td>
        <td><%= legal_case.isActive %></td>
        <td><%= legal_case.country %></td>
        
        <td><%= link_to 'Show', legal_case %></td>
        <td><%= link_to 'Edit', edit_legal_case_path(legal_case) %></td>
        <td><%= link_to 'Destroy', legal_case, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Legal Case', new_legal_case_path %>

app/views/legal_cases/new.html.erb
<h1>New Legal Case</h1>

<%= render 'form', legal_case: @legal_case %>

<%= link_to 'Back', legal_cases_path %>

app/views/legal_cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caseid:</strong>
  <%= @legal_case.caseID %>
</p>

<p>
  <strong>Isactive:</strong>
  <%= @legal_case.isActive %>
</p>

<p>
  <strong>Country:</strong>
  <%= @legal_case.country %>
</p>

<%= link_to 'Edit', edit_legal_case_path(@legal_case) %> |
<%= link_to 'Back', legal_cases_path %>